---
project_name: slinky

release:
  github:
    owner: skip-mev
    name: slinky
  prerelease: true

builds:
  - main: 'cmd/slinky/main.go'
    goos:
    - 'linux'
    - 'darwin'
    binary: 'slinky'
    id: 'slinky'
    ldflags:
      - "-X github.com/skip-mev/slinky/cmd/build.Build={{.Version}}"
  - main: 'cmd/slinky-config/main.go'
    goos:
    - 'linux'
    - 'darwin'
    binary: 'slinky-config'
    id: 'slinky-config'
archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - ./config/local/market.json
      - ./config/local/oracle.json
      - ./config/dydx/market.json
      - ./config/dydx/oracle.json
      - README.md

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

changelog:
  skip: false
  use: 'github'

checksum:
  disable: false
