{
 "title": "Slinky Oracle Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(side_car_api_http_status_code,job)"
    }
   },
   {
    "name": "chain_id",
    "label": "chain-id",
    "query": {
     "query": "label_values({job=\"$job\"},chain_id)"
    }
   },
   {
    "name": "ticker",
    "label": "Reported Ticker",
    "query": {
     "query": "label_values(app_prices{chain_id=\"$chain_id\"},ticker)"
    }
   },
   {
    "name": "id",
    "label": "Side Car Price Pair",
    "query": {
     "query": "label_values(side_car_aggregated_price{job=\"$job\"},id)"
    }
   },
   {
    "name": "provider",
    "label": "Data Provider",
    "query": {
     "query": "label_values(side_car_health_check_provider_updates_total{job=~\"$job\"},provider)"
    }
   },
   {
    "name": "valscon",
    "label": "Validator Address",
    "query": {
     "query": "label_values(app_report_status_per_validator{job=\"$job\"},validator)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary for ${chain_id}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{job=\"${job}\",chain_id=\"${chain_id}\"}",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Block Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_latest_block_height{job=\"${job}\",chain_id=\"${chain_id}\"}[5m])",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 / (rate(cometbft_consensus_latest_block_height{job=\"${job}\",chain_id=\"${chain_id}\"}[5m]))",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Total Transactions Since Restart",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{job=\"${job}\"}"
    }
   ]
  },
  {
   "title": "Transactions / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_num_txs{job=\"${job}\"}[5m])"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_power{job=\"${job}\"}",
     "legendFormat": "Voting Power"
    },
    {
     "expr": "avg(cometbft_consensus_validator_power{job=\"${job}\"}) / avg(cometbft_consensus_validators_power{job=\"${job}\"})",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cometbft_blocksync_syncing{job=\"${job}\",chain_id=\"${chain_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "On-Chain Success % in Range",
   "type": "stat",
   "description": "Successful app oracle responses as a percent of total in range",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(app_oracle_responses{job=\"${job}\",status=\"Success\"}[$__range])) / (increase(app_oracle_responses{job=\"${job}\"}[$__range]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Tickers Failing",
   "type": "stat",
   "description": "Number of ticker pairs your node is failing with no prices reported in 15 minutes",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (status) (rate(app_report_status_per_validator{job=\"${job}\",status=\"with_price\"}[15m]) == 0) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tickers Reported to Chain",
   "type": "stat",
   "description": "Total number of Tickers reported on-chain",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (ticker) (app_prices{job=\"${job}\",chain_id=\"${chain_id}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "On Chain Responses / sec",
   "type": "stat",
   "description": "Oracle responses per second - should be 1:1 with block rate",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(app_oracle_responses{job=\"${job}\",chain_id=\"${chain_id}\"}[1m])",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Side Car Price Pairs Failing",
   "type": "stat",
   "description": "Number of price pairs with no prices reported in 15 minutes",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (status) (rate(side_car_provider_status_responses_per_id{job=\"${job}\",status=\"success\"}[15m]) == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Bonded Tokens on Validator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{job=\"${job}\"}"
    }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cometbft_consensus_validator_missed_blocks{job=\"${job}\"}[1h]))   ",
     "legendFormat": "1 Hour"
    },
    {
     "expr": "sum(increase(cometbft_consensus_validator_missed_blocks{job=\"${job}\"}[24h]))",
     "legendFormat": "1 Day"
    },
    {
     "expr": "sum(increase(cometbft_consensus_validator_missed_blocks{job=\"${job}\"}[7d]))   ",
     "legendFormat": "7 Day"
    }
   ]
  },
  { "title": "On-Chain Reported Prices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "On-Chain Price by Ticker (USD)  - Filter Above",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "app_prices{job=~\"${job}\",chain_id=\"${chain_id}\",ticker=\"${ticker}\"} / 10^18",
     "legendFormat": "{{ticker}}"
    }
   ]
  },
  {
   "title": "App Report Status for ${valscon}",
   "type": "gauge",
   "description": "Success of submitting price for ticker per block time",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(app_report_status_per_validator{job=~\"${job}\",chain_id=\"${chain_id}\",ticker=\"${ticker}\",validator=\"${valscon}\"}[15m])) / on(chain_id) group_right(status,ticker) (rate(cometbft_consensus_latest_block_height{job=\"${job}\",chain_id=\"${chain_id}\"}[15m]))",
     "legendFormat": "{{status}} - {{ticker}}"
    }
   ]
  },
  {
   "title": "Validator Reported Prices for Ticker vs all Vals - filter by Reported Ticker and Val Address",
   "type": "timeseries",
   "description": "Your validator address is bolded",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "app_reports_per_validator{job=\"${job}\",chain_id=\"${chain_id}\",ticker=~\"${ticker}\",validator!=\"${valscon}\"} / 10^18",
     "legendFormat": "{{validator}} - {{ticker}}"
    },
    {
     "expr": "app_reports_per_validator{job=\"${job}\",chain_id=\"${chain_id}\",ticker=~\"${ticker}\",validator=\"${valscon}\"} / 10^18",
     "legendFormat": "{{validator}} - {{ticker}}"
    }
   ]
  },
  {
   "title": "Side Car Aggregated Prices Reported to Chain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Side Car Aggregated Price Pair - Filter Above",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "side_car_aggregated_price{job=\"${job}\",id=~\"${id}\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Side Car Latency to Blockchain (s)",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(app_oracle_response_latency_bucket{job=~\"${job}\",chain_id=\"${chain_id}\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Side Car Provider Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Failing Price Feeds by Provider",
   "type": "table",
   "description": "Price Feeds with no data in 15 minutes",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (provider,id) (rate(side_car_provider_status_responses_per_id{job=\"${job}\",status=\"success\"}[15m])) == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Side Car Provider Price vs On Chain Price - Filter by id and provider above ",
   "type": "timeseries",
   "description": "Bold line is on-chain price, thin lines are provider reported prices for pair. Filter via Side Car Price Pair",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "side_car_provider_price{job=\"${job}\",id=~\"${id}\",provider=~\"${provider}\"}",
     "legendFormat": "{{id}} - {{provider}}"
    },
    {
     "expr": "app_prices{job=\"${job}\",ticker=~\"${id}\"} / 10^18",
     "legendFormat": "On Chain Price - {{ticker}}"
    }
   ]
  },
  {
   "title": "Data Provider Success % in Range",
   "type": "stat",
   "description": "Percentage of requests from sidecar to data provider that were successful in the time range of the dashboard",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (provider) (increase(side_car_provider_status_responses_per_id{job=\"${job}\",status=\"success\"}[$__range])) / sum by (provider) (increase(side_car_provider_status_responses_per_id{job=\"${job}\"}[$__range]))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Data Provider Success % - Filter Above",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (provider) (increase(side_car_provider_status_responses_per_id{job=\"${job}\",status=\"success\"}[$__range])) / sum by (provider) (increase(side_car_provider_status_responses_per_id{job=\"${job}\"}[$__range]))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  { "title": "Blockchain Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Block Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_block_interval_seconds_sum{chain_id=\"${chain_id}\"}[1m]) / rate(cometbft_consensus_block_interval_seconds_count{chain_id=\"${chain_id}\"}[1m])",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{chain_id=\"${chain_id}\"}",
     "legendFormat": "Block size"
    }
   ]
  },
  {
   "title": "ABCI Method Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cometbft_abci_connection_method_timing_seconds_sum{job=\"${job}\"}[1m]) / rate(cometbft_abci_connection_method_timing_seconds_count{job=\"${job}\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "ABCI Method Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(app_abci_method_latency_sum{chain_id=\"${chain_id}\"}[1m]) / rate(app_abci_method_latency_count{chain_id=\"${chain_id}\"}[1m])",
     "legendFormat": "{{abci_method}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{job=\"$job\"}",
     "legendFormat": "Peers - {{instance}}"
    }
   ]
  },
  {
   "title": "Txs/block",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Transactions / sec (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(cometbft_mempool_failed_txs{job=\"${job}\",chain_id=\"${chain_id}\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{job=\"${job}\",chain_id=\"${chain_id}\"}",
     "legendFormat": "Mempool"
    }
   ]
  },
  {
   "title": "Detailed Side Car Provider Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 }
  },
  {
   "title": "Detailed Data for ${provider} - Request Success % by Price Pair, Provider and Route",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
   "repeat": "provider",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (provider,id,type) (increase(side_car_provider_status_responses_per_id{job=\"${job}\",provider=~\"${provider}\",status=\"success\"}[5m]))) / (sum by (provider,id,type) (increase(side_car_provider_status_responses_per_id{job=\"${job}\",provider=~\"${provider}\",}[5m])))",
     "legendFormat": "{{id}} - {{type}}"
    }
   ]
  }
 ]
}