package constants

import (
	pkgtypes "github.com/skip-mev/slinky/pkg/types"
)

var (
	// The following are the default currency pairs for the oracle sidecar.
	//
	// USD denominated tickers.
	APE_USD       = pkgtypes.NewCurrencyPair("APE", "USD")
	APTOS_USD     = pkgtypes.NewCurrencyPair("APT", "USD")
	ARBITRUM_USD  = pkgtypes.NewCurrencyPair("ARB", "USD")
	ATOM_USD      = pkgtypes.NewCurrencyPair("ATOM", "USD")
	AVAX_USD      = pkgtypes.NewCurrencyPair("AVAX", "USD")
	BCH_USD       = pkgtypes.NewCurrencyPair("BCH", "USD")
	BITCOIN_USD   = pkgtypes.NewCurrencyPair("BTC", "USD")
	BLUR_USD      = pkgtypes.NewCurrencyPair("BLUR", "USD")
	CARDANO_USD   = pkgtypes.NewCurrencyPair("ADA", "USD")
	CELESTIA_USD  = pkgtypes.NewCurrencyPair("TIA", "USD")
	CHAINLINK_USD = pkgtypes.NewCurrencyPair("LINK", "USD")
	COMPOUND_USD  = pkgtypes.NewCurrencyPair("COMP", "USD")
	CURVE_USD     = pkgtypes.NewCurrencyPair("CRV", "USD")
	DOGE_USD      = pkgtypes.NewCurrencyPair("DOGE", "USD")
	DYDX_USD      = pkgtypes.NewCurrencyPair("DYDX", "USD")
	ETC_USD       = pkgtypes.NewCurrencyPair("ETC", "USD")
	ETHEREUM_USD  = pkgtypes.NewCurrencyPair("ETH", "USD")
	FILECOIN_USD  = pkgtypes.NewCurrencyPair("FIL", "USD")
	LIDO_USD      = pkgtypes.NewCurrencyPair("LDO", "USD")
	LITECOIN_USD  = pkgtypes.NewCurrencyPair("LTC", "USD")
	MAKER_USD     = pkgtypes.NewCurrencyPair("MKR", "USD")
	MOG_USD       = pkgtypes.NewCurrencyPair("MOG", "USD")
	NEAR_USD      = pkgtypes.NewCurrencyPair("NEAR", "USD")
	OPTIMISM_USD  = pkgtypes.NewCurrencyPair("OP", "USD")
	OSMOSIS_USD   = pkgtypes.NewCurrencyPair("OSMO", "USD")
	PEPE_USD      = pkgtypes.NewCurrencyPair("PEPE", "USD")
	POLKADOT_USD  = pkgtypes.NewCurrencyPair("DOT", "USD")
	POLYGON_USD   = pkgtypes.NewCurrencyPair("MATIC", "USD")
	RIPPLE_USD    = pkgtypes.NewCurrencyPair("XRP", "USD")
	SEI_USD       = pkgtypes.NewCurrencyPair("SEI", "USD")
	SHIBA_USD     = pkgtypes.NewCurrencyPair("SHIB", "USD")
	SOLANA_USD    = pkgtypes.NewCurrencyPair("SOL", "USD")
	STELLAR_USD   = pkgtypes.NewCurrencyPair("XLM", "USD")
	SUI_USD       = pkgtypes.NewCurrencyPair("SUI", "USD")
	TRON_USD      = pkgtypes.NewCurrencyPair("TRX", "USD")
	UNISWAP_USD   = pkgtypes.NewCurrencyPair("UNI", "USD")
	USDC_USD      = pkgtypes.NewCurrencyPair("USDC", "USD")
	USDT_USD      = pkgtypes.NewCurrencyPair("USDT", "USD")
	WORLD_USD     = pkgtypes.NewCurrencyPair("WLD", "USD")

	// USDC denominated tickers.
	APE_USDC       = pkgtypes.NewCurrencyPair("APE", "USDC")
	APTOS_USDC     = pkgtypes.NewCurrencyPair("APT", "USDC")
	ARBITRUM_USDC  = pkgtypes.NewCurrencyPair("ARB", "USDC")
	ATOM_USDC      = pkgtypes.NewCurrencyPair("ATOM", "USDC")
	AVAX_USDC      = pkgtypes.NewCurrencyPair("AVAX", "USDC")
	BCH_USDC       = pkgtypes.NewCurrencyPair("BCH", "USDC")
	BITCOIN_USDC   = pkgtypes.NewCurrencyPair("BTC", "USDC")
	BLUR_USDC      = pkgtypes.NewCurrencyPair("BLUR", "USDC")
	CARDANO_USDC   = pkgtypes.NewCurrencyPair("ADA", "USDC")
	CELESTIA_USDC  = pkgtypes.NewCurrencyPair("TIA", "USDC")
	CHAINLINK_USDC = pkgtypes.NewCurrencyPair("LINK", "USDC")
	COMPOUND_USDC  = pkgtypes.NewCurrencyPair("COMP", "USDC")
	CURVE_USDC     = pkgtypes.NewCurrencyPair("CRV", "USDC")
	DOGE_USDC      = pkgtypes.NewCurrencyPair("DOGE", "USDC")
	DYDX_USDC      = pkgtypes.NewCurrencyPair("DYDX", "USDC")
	ETC_USDC       = pkgtypes.NewCurrencyPair("ETC", "USDC")
	ETHEREUM_USDC  = pkgtypes.NewCurrencyPair("ETH", "USDC")
	FILECOIN_USDC  = pkgtypes.NewCurrencyPair("FIL", "USDC")
	LIDO_USDC      = pkgtypes.NewCurrencyPair("LDO", "USDC")
	LITECOIN_USDC  = pkgtypes.NewCurrencyPair("LTC", "USDC")
	MAKER_USDC     = pkgtypes.NewCurrencyPair("MKR", "USDC")
	MOG_USDC       = pkgtypes.NewCurrencyPair("MOG", "USDC")
	NEAR_USDC      = pkgtypes.NewCurrencyPair("NEAR", "USDC")
	OPTIMISM_USDC  = pkgtypes.NewCurrencyPair("OP", "USDC")
	OSMOSIS_USDC   = pkgtypes.NewCurrencyPair("OSMO", "USDC")
	PEPE_USDC      = pkgtypes.NewCurrencyPair("PEPE", "USDC")
	POLKADOT_USDC  = pkgtypes.NewCurrencyPair("DOT", "USDC")
	POLYGON_USDC   = pkgtypes.NewCurrencyPair("MATIC", "USDC")
	RIPPLE_USDC    = pkgtypes.NewCurrencyPair("XRP", "USDC")
	SEI_USDC       = pkgtypes.NewCurrencyPair("SEI", "USDC")
	SHIBA_USDC     = pkgtypes.NewCurrencyPair("SHIB", "USDC")
	SOLANA_USDC    = pkgtypes.NewCurrencyPair("SOL", "USDC")
	STELLAR_USDC   = pkgtypes.NewCurrencyPair("XLM", "USDC")
	SUI_USDC       = pkgtypes.NewCurrencyPair("SUI", "USDC")
	TRON_USDC      = pkgtypes.NewCurrencyPair("TRX", "USDC")
	UNISWAP_USDC   = pkgtypes.NewCurrencyPair("UNI", "USDC")
	WORLD_USDC     = pkgtypes.NewCurrencyPair("WLD", "USDC")

	// USDT denominated tickers.
	APE_USDT       = pkgtypes.NewCurrencyPair("APE", "USDT")
	APTOS_USDT     = pkgtypes.NewCurrencyPair("APT", "USDT")
	ARBITRUM_USDT  = pkgtypes.NewCurrencyPair("ARB", "USDT")
	ATOM_USDT      = pkgtypes.NewCurrencyPair("ATOM", "USDT")
	AVAX_USDT      = pkgtypes.NewCurrencyPair("AVAX", "USDT")
	BCH_USDT       = pkgtypes.NewCurrencyPair("BCH", "USDT")
	BITCOIN_USDT   = pkgtypes.NewCurrencyPair("BTC", "USDT")
	BLUR_USDT      = pkgtypes.NewCurrencyPair("BLUR", "USDT")
	CARDANO_USDT   = pkgtypes.NewCurrencyPair("ADA", "USDT")
	CELESTIA_USDT  = pkgtypes.NewCurrencyPair("TIA", "USDT")
	CHAINLINK_USDT = pkgtypes.NewCurrencyPair("LINK", "USDT")
	COMPOUND_USDT  = pkgtypes.NewCurrencyPair("COMP", "USDT")
	CURVE_USDT     = pkgtypes.NewCurrencyPair("CRV", "USDT")
	DOGE_USDT      = pkgtypes.NewCurrencyPair("DOGE", "USDT")
	DYDX_USDT      = pkgtypes.NewCurrencyPair("DYDX", "USDT")
	ETC_USDT       = pkgtypes.NewCurrencyPair("ETC", "USDT")
	ETHEREUM_USDT  = pkgtypes.NewCurrencyPair("ETH", "USDT")
	FILECOIN_USDT  = pkgtypes.NewCurrencyPair("FIL", "USDT")
	LIDO_USDT      = pkgtypes.NewCurrencyPair("LDO", "USDT")
	LITECOIN_USDT  = pkgtypes.NewCurrencyPair("LTC", "USDT")
	MAKER_USDT     = pkgtypes.NewCurrencyPair("MKR", "USDT")
	MOG_USDT       = pkgtypes.NewCurrencyPair("MOG", "USDT")
	NEAR_USDT      = pkgtypes.NewCurrencyPair("NEAR", "USDT")
	OPTIMISM_USDT  = pkgtypes.NewCurrencyPair("OP", "USDT")
	OSMOSIS_USDT   = pkgtypes.NewCurrencyPair("OSMO", "USDT")
	PEPE_USDT      = pkgtypes.NewCurrencyPair("PEPE", "USDT")
	POLKADOT_USDT  = pkgtypes.NewCurrencyPair("DOT", "USDT")
	POLYGON_USDT   = pkgtypes.NewCurrencyPair("MATIC", "USDT")
	RIPPLE_USDT    = pkgtypes.NewCurrencyPair("XRP", "USDT")
	SEI_USDT       = pkgtypes.NewCurrencyPair("SEI", "USDT")
	SHIBA_USDT     = pkgtypes.NewCurrencyPair("SHIB", "USDT")
	SOLANA_USDT    = pkgtypes.NewCurrencyPair("SOL", "USDT")
	STELLAR_USDT   = pkgtypes.NewCurrencyPair("XLM", "USDT")
	SUI_USDT       = pkgtypes.NewCurrencyPair("SUI", "USDT")
	TRON_USDT      = pkgtypes.NewCurrencyPair("TRX", "USDT")
	UNISWAP_USDT   = pkgtypes.NewCurrencyPair("UNI", "USDT")
	USDC_USDT      = pkgtypes.NewCurrencyPair("USDC", "USDT")
	WORLD_USDT     = pkgtypes.NewCurrencyPair("WLD", "USDT")

	// BTC denominated tickers.
	ETHEREUM_BITCOIN = pkgtypes.NewCurrencyPair("ETH", "BTC")
)
