{
 "title": "Slinky dYdX Oracle Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(side_car_api_http_status_code,job)"
    }
   },
   {
    "name": "chain_id",
    "label": "chain-id",
    "query": {
     "query": "label_values({job=\"$job\"},chain_id)"
    }
   },
   {
    "name": "ticker",
    "label": "Reported Ticker",
    "query": {
     "query": "label_values(pricefeed_server_valid_prices_count{job=\"$job\"},market_id)"
    }
   },
   {
    "name": "id",
    "label": "Side Car Price Pair",
    "query": {
     "query": "label_values(side_car_aggregated_price{job=\"$job\"},id)"
    }
   },
   {
    "name": "provider",
    "label": "Data Provider",
    "query": {
     "query": "label_values(side_car_health_check_provider_updates_total{job=~\"$job\"},provider)"
    }
   },
   {
    "name": "valscon",
    "label": "Validator Address",
    "query": {
     "query": "label_values(app_report_status_per_validator{job=\"$job\"},validator)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cometbft_consensus_height{job=\"$job\"},instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Summary for ${chain_id}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{job=\"${job}\",chain_id=\"${chain_id}\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Block Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(cometbft_consensus_latest_block_height{job=\"${job}\",chain_id=\"${chain_id}\"}[5m]))",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(1 / (rate(cometbft_consensus_latest_block_height{job=\"${job}\",chain_id=\"${chain_id}\"}[5m])))",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Total Transactions Since Restart",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cometbft_consensus_num_txs{job=\"${job}\"})"
    }
   ]
  },
  {
   "title": "Transactions / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(cometbft_consensus_num_txs{job=\"${job}\"}[5m]))"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cometbft_consensus_validator_power{job=\"${job}\"})",
     "legendFormat": "Voting Power"
    },
    {
     "expr": "avg(cometbft_consensus_validator_power{job=\"${job}\"}) / avg(cometbft_consensus_validators_power{job=\"${job}\"})",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Node State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cometbft_blocksync_syncing{job=\"${job}\",chain_id=\"${chain_id}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tickers With No Updates in...",
   "type": "stat",
   "description": "Number of ticker pairs without an update in 1 hour.  This may not be an issue, but price changes haven't deviated enough for an update.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(changes(prices_current_market_prices{job=\"${job}\",instance=\"${instance}\"}[15m]) == 0)",
     "legendFormat": "15m"
    },
    {
     "expr": "count(changes(prices_current_market_prices{job=\"${job}\",instance=\"${instance}\"}[1h]) == 0)",
     "legendFormat": "1h"
    },
    {
     "expr": "count(changes(prices_current_market_prices{job=\"${job}\",instance=\"${instance}\"}[3h]) == 0)",
     "legendFormat": "3h"
    },
    {
     "expr": "count(changes(prices_current_market_prices{job=\"${job}\",instance=\"${instance}\"}[6h]) == 0)",
     "legendFormat": "6h"
    }
   ]
  },
  {
   "title": "Price Pairs Reported From SideCar",
   "type": "stat",
   "description": "Total number of Price Pairs reported from SideCar",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pricefeed_server_valid_prices_count{job=\"${job}\",instance=\"${instance}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "On Chain Responses / sec",
   "type": "stat",
   "description": "Oracle responses per second - should be 1:1 with block rate",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(app_oracle_responses{job=\"${job}\",chain_id=\"${chain_id}\",status=\"Success\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Failing Sidecar Pairs",
   "type": "stat",
   "description": "Total ",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(pricefeed_server_update_price_valid_count{job=\"${job}\"}[15m]) == 0)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total Bonded Tokens on Validator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cometbft_consensus_validators_power{job=\"${job}\"})"
    }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cometbft_consensus_validator_missed_blocks{job=\"${job}\",instance=\"${instance}\"}[1h]))",
     "legendFormat": "1 Hour"
    },
    {
     "expr": "sum(increase(cometbft_consensus_validator_missed_blocks{job=\"${job}\",instance=\"${instance}\"}[24h]))",
     "legendFormat": "1 Day"
    },
    {
     "expr": "sum(increase(cometbft_consensus_validator_missed_blocks{job=\"${job}\",instance=\"${instance}\"}[7d]))",
     "legendFormat": "7 Day"
    }
   ]
  },
  { "title": "On-Chain Reported Prices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "On-Chain Price by Reported Ticker (USD)  - Filter Above",
   "type": "timeseries",
   "description": "Reported prices on-chain.  Prices changes only reported when % deviation is met, so graph will be incomplete",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "prices_current_market_prices{job=\"${job}\",instance=\"${instance}\",market_id=~\"${ticker}\"}",
     "legendFormat": "{{market_id}}"
    }
   ]
  },
  {
   "title": "Latest Price Pair Reports by instance",
   "type": "table",
   "description": "Last Price Reports and",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{job=\"${job}\",instance=\"${instance}\"} - on (job) group_right last_over_time(prices_last_price_update_for_market_block{job=\"${job}\",instance=\"${instance}\"}[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to Update Market Prices",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(update_market_prices_latency_sum{job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "Price Latency - {{ instance }}"
    }
   ]
  },
  {
   "title": "Vote Extension Latency (s) by instance",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(app_abci_method_latency_bucket{abci_method=\"verify_vote_extension\",job=~\"${job}\",chain_id=\"${chain_id}\",instance=\"${instance}\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vote Extension Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(app_abci_method_latency_sum{abci_method=\"verify_vote_extension\",job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "Vote Extension Latency - {{ instance }}"
    }
   ]
  },
  {
   "title": "Side Car Aggregated Prices Reported to Chain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "Side Car Aggregated Price Pair - Filter Above",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "side_car_aggregated_price{job=\"${job}\",id=~\"${id}\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Side Car Latency to Blockchain (s) by instance",
   "type": "heatmap",
   "description": "Latency between validator node and sidecar",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(app_oracle_response_latency_bucket{job=~\"${job}\",chain_id=\"${chain_id}\",instance=\"${instance}\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Side Car Provider Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Failing Price Feeds by Provider",
   "type": "table",
   "description": "Price Feeds with no data in 15 minutes",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (provider,id) (rate(side_car_provider_status_responses_per_id{job=\"${job}\",status=\"success\"}[15m])) == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Side Car Provider Price vs On Chain Price - Filter by id and provider above ",
   "type": "timeseries",
   "description": "Bold line is on-chain price, thin lines are provider reported prices for pair. Filter via Side Car Price Pair",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "side_car_provider_price{job=\"${job}\",id=~\"${id}\",provider=~\"${provider}\"}",
     "legendFormat": "{{id}} - {{provider}}"
    },
    {
     "expr": "app_prices{job=\"${job}\",ticker=~\"${id}\"} / 10^18",
     "legendFormat": "On Chain Price - {{ticker}}"
    }
   ]
  },
  {
   "title": "Data Provider Success % in Range",
   "type": "stat",
   "description": "Percentage of requests from sidecar to data provider that were successful in the time range of the dashboard",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (provider) (increase(side_car_provider_status_responses_per_id{job=\"${job}\",status=\"success\"}[$__range])) / sum by (provider) (increase(side_car_provider_status_responses_per_id{job=\"${job}\"}[$__range]))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Data Provider Success % - Filter Above",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (provider) (increase(side_car_provider_status_responses_per_id{job=\"${job}\",status=\"success\"}[$__range])) / sum by (provider) (increase(side_car_provider_status_responses_per_id{job=\"${job}\"}[$__range]))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  { "title": "Blockchain Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Block Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_block_interval_seconds_sum{chain_id=\"${chain_id}\"}[1m]) / rate(cometbft_consensus_block_interval_seconds_count{chain_id=\"${chain_id}\"}[1m])",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{chain_id=\"${chain_id}\"}",
     "legendFormat": "Block size"
    }
   ]
  },
  {
   "title": "ABCI Method Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cometbft_abci_connection_method_timing_seconds_sum{job=\"${job}\"}[1m]) / rate(cometbft_abci_connection_method_timing_seconds_count{job=\"${job}\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "ABCI Method Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(app_abci_method_latency_sum{chain_id=\"${chain_id}\"}[1m]) / rate(app_abci_method_latency_count{chain_id=\"${chain_id}\"}[1m])",
     "legendFormat": "{{abci_method}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{job=\"$job\"}",
     "legendFormat": "Peers - {{instance}}"
    }
   ]
  },
  {
   "title": "Txs/block",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Transactions / sec (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(cometbft_mempool_failed_txs{job=\"${job}\",chain_id=\"${chain_id}\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{job=\"${job}\",chain_id=\"${chain_id}\"}",
     "legendFormat": "Mempool"
    }
   ]
  },
  {
   "title": "Detailed Side Car Provider Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 }
  },
  {
   "title": "Detailed Data for ${provider} - Request Success % by Price Pair, Provider and Route",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
   "repeat": "provider",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (provider,id,type) (increase(side_car_provider_status_responses_per_id{job=\"${job}\",provider=~\"${provider}\",status=\"success\"}[5m]))) / (sum by (provider,id,type) (increase(side_car_provider_status_responses_per_id{job=\"${job}\",provider=~\"${provider}\",}[5m])))",
     "legendFormat": "{{id}} - {{type}}"
    }
   ]
  }
 ]
}