// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BlockAgeChecker is an autogenerated mock type for the BlockAgeChecker type
type BlockAgeChecker struct {
	mock.Mock
}

// IsHeightValid provides a mock function with given fields: newHeight
func (_m *BlockAgeChecker) IsHeightValid(newHeight uint64) bool {
	ret := _m.Called(newHeight)

	if len(ret) == 0 {
		panic("no return value specified for IsHeightValid")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(uint64) bool); ok {
		r0 = rf(newHeight)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewBlockAgeChecker creates a new instance of BlockAgeChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlockAgeChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlockAgeChecker {
	mock := &BlockAgeChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
