// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	oracletypes "github.com/skip-mev/slinky/x/oracle/types"

	types "github.com/cosmos/cosmos-sdk/types"
)

// Keeper is an autogenerated mock type for the Keeper type
type Keeper struct {
	mock.Mock
}

// GetAllCurrencyPairs provides a mock function with given fields: ctx
func (_m *Keeper) GetAllCurrencyPairs(ctx types.Context) []oracletypes.CurrencyPair {
	ret := _m.Called(ctx)

	var r0 []oracletypes.CurrencyPair
	if rf, ok := ret.Get(0).(func(types.Context) []oracletypes.CurrencyPair); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]oracletypes.CurrencyPair)
		}
	}

	return r0
}

// SetPriceForCurrencyPair provides a mock function with given fields: ctx, cp, qp
func (_m *Keeper) SetPriceForCurrencyPair(ctx types.Context, cp oracletypes.CurrencyPair, qp oracletypes.QuotePrice) error {
	ret := _m.Called(ctx, cp, qp)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Context, oracletypes.CurrencyPair, oracletypes.QuotePrice) error); ok {
		r0 = rf(ctx, cp, qp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKeeper creates a new instance of Keeper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeeper(t interface {
	mock.TestingT
	Cleanup(func())
}) *Keeper {
	mock := &Keeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
