{
 "title": "Slinky SideCar Dashboard Local",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "chain_id",
    "label": "chain-id",
    "query": {
     "query": "label_values({job=\"$job\"},chain_id)"
    }
   },
   {
    "name": "ticker",
    "label": "Reported Ticker",
    "query": {
     "query": "label_values(app_prices,ticker)"
    }
   },
   {
    "name": "id",
    "label": "Side Car Price Pair",
    "query": {
     "query": "label_values(side_car_aggregated_price,id)"
    }
   },
   {
    "name": "provider",
    "label": "Price Data Provider",
    "query": {
     "query": "label_values(side_car_health_check_provider_updates_total,provider)"
    }
   },
   {
    "name": "validator",
    "label": "Validator Consensus Address",
    "query": {
     "query": "label_values(app_reports_per_validator,validator)"
    }
   },
   {
    "name": "market_map_provider",
    "label": "Market Map Data Provider",
    "query": {
     "query": "label_values(side_car_provider_status_responses_per_id,provider)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Side Car Aggregated Prices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Side Car Price Updates in Range",
   "type": "stat",
   "description": "The number times per second that the side-car attempts to calculate a final price from all of the providers in range.",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(side_car_health_check_system_updates_total{job=\"${job}\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Price Update % in Range",
   "type": "stat",
   "description": "Percentage of successful price updates relative to the expected number of updates in range.",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (id) \n(rate(side_car_health_check_ticker_updates_total{job=\"${job}\"}[$__range]))\n/\nscalar(rate(side_car_health_check_system_updates_total{job=\"${job}\"}[$__range]))",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Side Car Aggregated Price Pair - Filter Above",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "side_car_aggregated_price{job=\"${job}\",id=~\"${id}\"}",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "side_car_provider_price{job=\"${job}\",id=~\"${id}\"}",
     "legendFormat": "{{id}} {{provider}}"
    }
   ]
  },
  { "title": "Side Car Provider Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Data Provider HTTP 2XX % in Range",
   "type": "stat",
   "description": "Percentage of requests from sidecar to data provider that were successful in the time range of the dashboard",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (provider) (increase(side_car_api_http_status_code{job=\"${job}\",status_code=\"2XX\"}[$__range]))) / (sum by (provider) (increase(side_car_api_http_status_code{job=\"${job}\"}[$__range])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Data Provider Successful WebSocket Message Handling % in Range",
   "type": "stat",
   "description": "Percentage of web socket messages from sidecar to data provider that were successful handled in the time range of the dashboard.",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (provider) (increase(side_car_web_socket_data_handler_status{job=\"${job}\",status=~\"create_message_success|handle_message_success|heartbeat_success\"}[$__range]))) / (sum by (provider) (increase(side_car_web_socket_data_handler_status{job=\"${job}\"}[$__range])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Data Provider HTTP Status Code / sec",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(side_car_api_http_status_code{job=\"${job}\"}[$__range])) by (status_code,provider)",
     "legendFormat": "{{provider}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Data Provider Successful WebSocket Connection Reads % in Range",
   "type": "stat",
   "description": "Percentage of reads that were successfully made on the underlying connection by the data provider in the range.",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (provider) (increase(side_car_web_socket_connection_status{job=\"${job}\",status=~\"read_success\"}[$__range]))) / (sum by (provider) (increase(side_car_web_socket_connection_status{job=\"${job}\",status=~\"read_success|read_err\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Provider Successful WebSocket Connection Writes % in Range",
   "type": "stat",
   "description": "The percentage of successful writes made by web socket data providers in the range.",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (provider) (increase(side_car_web_socket_connection_status{job=\"${job}\",status=~\"write_success\"}[$__range]))) / (sum by (provider) (increase(side_car_web_socket_connection_status{job=\"${job}\",status=~\"write_success|write_err\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Detailed Side Car Provider Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 }
  },
  {
   "title": "Data Provider ${provider} Fetch Success % in Range",
   "type": "stat",
   "description": "Percentage of how often we were able to successfully retrieve a price from a provider per market when expected.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "repeat": "provider",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (provider, id) (increase(side_car_health_check_provider_updates_total{job=\"${job}\", success=\"true\", provider=~\"${provider}\"}[$__range])) / sum by (provider, id) (increase(side_car_health_check_provider_updates_total{job=\"${job}\", provider=~\"${provider}\"}[$__range])))",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}