// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	handlers "github.com/skip-mev/slinky/providers/base/websocket/handlers"
	mock "github.com/stretchr/testify/mock"

	types "github.com/skip-mev/slinky/providers/types"
)

// WebSocketDataHandler is an autogenerated mock type for the WebSocketDataHandler type
type WebSocketDataHandler[K comparable, V interface{}] struct {
	mock.Mock
}

// CreateMessages provides a mock function with given fields: ids
func (_m *WebSocketDataHandler[K, V]) CreateMessages(ids []K) ([]handlers.WebsocketEncodedMessage, error) {
	ret := _m.Called(ids)

	var r0 []handlers.WebsocketEncodedMessage
	var r1 error
	if rf, ok := ret.Get(0).(func([]K) ([]handlers.WebsocketEncodedMessage, error)); ok {
		return rf(ids)
	}
	if rf, ok := ret.Get(0).(func([]K) []handlers.WebsocketEncodedMessage); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]handlers.WebsocketEncodedMessage)
		}
	}

	if rf, ok := ret.Get(1).(func([]K) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleMessage provides a mock function with given fields: message
func (_m *WebSocketDataHandler[K, V]) HandleMessage(message []byte) (types.GetResponse[K, V], []byte, error) {
	ret := _m.Called(message)

	var r0 types.GetResponse[K, V]
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func([]byte) (types.GetResponse[K, V], []byte, error)); ok {
		return rf(message)
	}
	if rf, ok := ret.Get(0).(func([]byte) types.GetResponse[K, V]); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Get(0).(types.GetResponse[K, V])
	}

	if rf, ok := ret.Get(1).(func([]byte) []byte); ok {
		r1 = rf(message)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func([]byte) error); ok {
		r2 = rf(message)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Name provides a mock function with given fields:
func (_m *WebSocketDataHandler[K, V]) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// URL provides a mock function with given fields:
func (_m *WebSocketDataHandler[K, V]) URL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewWebSocketDataHandler creates a new instance of WebSocketDataHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebSocketDataHandler[K comparable, V interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *WebSocketDataHandler[K, V] {
	mock := &WebSocketDataHandler[K, V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
