// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: slinky/marketmap/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GetMarketMapRequest is the query request for the GetMarketMap query.
// It takes no arguments.
type GetMarketMapRequest struct {
}

func (m *GetMarketMapRequest) Reset()         { *m = GetMarketMapRequest{} }
func (m *GetMarketMapRequest) String() string { return proto.CompactTextString(m) }
func (*GetMarketMapRequest) ProtoMessage()    {}
func (*GetMarketMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5d6ff68f3c474a0, []int{0}
}
func (m *GetMarketMapRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetMarketMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetMarketMapRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetMarketMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketMapRequest.Merge(m, src)
}
func (m *GetMarketMapRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetMarketMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketMapRequest proto.InternalMessageInfo

// GetMarketMapResponse is the query response for the GetMarketMap query.
type GetMarketMapResponse struct {
	// MarketMap defines the global set of market configurations for all providers
	// and markets.
	MarketMap TickersConfig `protobuf:"bytes,1,opt,name=market_map,json=marketMap,proto3" json:"market_map"`
	// LastUpdated is the last block height that the market map was updated.
	// This field can be used as an optimization for clients checking if there
	// is a new update to the map.
	LastUpdated int64 `protobuf:"varint,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
}

func (m *GetMarketMapResponse) Reset()         { *m = GetMarketMapResponse{} }
func (m *GetMarketMapResponse) String() string { return proto.CompactTextString(m) }
func (*GetMarketMapResponse) ProtoMessage()    {}
func (*GetMarketMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5d6ff68f3c474a0, []int{1}
}
func (m *GetMarketMapResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetMarketMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetMarketMapResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetMarketMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketMapResponse.Merge(m, src)
}
func (m *GetMarketMapResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetMarketMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketMapResponse proto.InternalMessageInfo

func (m *GetMarketMapResponse) GetMarketMap() TickersConfig {
	if m != nil {
		return m.MarketMap
	}
	return TickersConfig{}
}

func (m *GetMarketMapResponse) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func init() {
	proto.RegisterType((*GetMarketMapRequest)(nil), "slinky.marketmap.v1.GetMarketMapRequest")
	proto.RegisterType((*GetMarketMapResponse)(nil), "slinky.marketmap.v1.GetMarketMapResponse")
}

func init() { proto.RegisterFile("slinky/marketmap/v1/query.proto", fileDescriptor_b5d6ff68f3c474a0) }

var fileDescriptor_b5d6ff68f3c474a0 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4e, 0x32, 0x31,
	0x14, 0xc5, 0xa7, 0x7c, 0x9f, 0x26, 0x16, 0x56, 0x03, 0x26, 0x84, 0x98, 0x32, 0xce, 0xc2, 0x60,
	0xa2, 0xd3, 0x80, 0x6f, 0x80, 0x89, 0xac, 0x58, 0x48, 0x74, 0xe3, 0x86, 0x14, 0xa8, 0xb5, 0x19,
	0xfa, 0x87, 0x69, 0x87, 0xc8, 0x96, 0xad, 0x1b, 0x13, 0xe3, 0x3b, 0xb1, 0x24, 0x71, 0xe3, 0xca,
	0x18, 0xf0, 0x41, 0x0c, 0x54, 0x0c, 0x26, 0x63, 0xe2, 0xae, 0x3d, 0xf7, 0xd7, 0x73, 0xef, 0x3d,
	0x85, 0x55, 0x33, 0xe4, 0x32, 0x9e, 0x60, 0x41, 0x92, 0x98, 0x5a, 0x41, 0x34, 0x1e, 0xd7, 0xf1,
	0x28, 0xa5, 0xc9, 0x24, 0xd2, 0x89, 0xb2, 0xca, 0x2f, 0x3a, 0x20, 0xfa, 0x06, 0xa2, 0x71, 0xbd,
	0x52, 0x62, 0x8a, 0xa9, 0x75, 0x1d, 0xaf, 0x4e, 0x0e, 0xad, 0x1c, 0x30, 0xa5, 0xd8, 0x90, 0x62,
	0xa2, 0x39, 0x26, 0x52, 0x2a, 0x4b, 0x2c, 0x57, 0xd2, 0x7c, 0x55, 0x83, 0xac, 0x4e, 0xee, 0xe2,
	0x88, 0x70, 0x1f, 0x16, 0x5b, 0xd4, 0xb6, 0xd7, 0x52, 0x9b, 0xe8, 0x0e, 0x1d, 0xa5, 0xd4, 0xd8,
	0x70, 0x0a, 0x60, 0xe9, 0xa7, 0x6e, 0xb4, 0x92, 0x86, 0xfa, 0x2d, 0x08, 0xdd, 0xfb, 0xae, 0x20,
	0xba, 0x0c, 0x02, 0x50, 0xcb, 0x37, 0xc2, 0x28, 0x63, 0xde, 0xe8, 0x8a, 0xf7, 0x63, 0x9a, 0x98,
	0x73, 0x25, 0x6f, 0x39, 0x6b, 0xfe, 0x9f, 0xbd, 0x55, 0xbd, 0xce, 0x9e, 0xd8, 0x18, 0xfa, 0x87,
	0xb0, 0x30, 0x24, 0xc6, 0x76, 0x53, 0x3d, 0x20, 0x96, 0x0e, 0xca, 0xb9, 0x00, 0xd4, 0xfe, 0x75,
	0xf2, 0x2b, 0xed, 0xda, 0x49, 0x8d, 0x67, 0x00, 0x77, 0x2e, 0x57, 0xb1, 0xf8, 0x0f, 0x00, 0x16,
	0xb6, 0xc7, 0xf1, 0x6b, 0x99, 0x2d, 0x33, 0x36, 0xa9, 0x1c, 0xff, 0x81, 0x74, 0xbb, 0x85, 0x47,
	0xd3, 0x97, 0x8f, 0xa7, 0x5c, 0xe0, 0x23, 0xfc, 0x7b, 0x6c, 0x82, 0xe8, 0xe6, 0xc5, 0x6c, 0x81,
	0xc0, 0x7c, 0x81, 0xc0, 0xfb, 0x02, 0x81, 0xc7, 0x25, 0xf2, 0xe6, 0x4b, 0xe4, 0xbd, 0x2e, 0x91,
	0x77, 0x73, 0xc2, 0xb8, 0xbd, 0x4b, 0x7b, 0x51, 0x5f, 0x09, 0x6c, 0x62, 0xae, 0x4f, 0x05, 0x1d,
	0x6f, 0xcc, 0xee, 0xb7, 0xec, 0xec, 0x44, 0x53, 0xd3, 0xdb, 0x5d, 0x7f, 0xc1, 0xd9, 0x67, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xf7, 0x01, 0x50, 0x90, 0x10, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// GetMarketMap returns the full market map stored in the x/marketmap
	// module.
	GetMarketMap(ctx context.Context, in *GetMarketMapRequest, opts ...grpc.CallOption) (*GetMarketMapResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetMarketMap(ctx context.Context, in *GetMarketMapRequest, opts ...grpc.CallOption) (*GetMarketMapResponse, error) {
	out := new(GetMarketMapResponse)
	err := c.cc.Invoke(ctx, "/slinky.marketmap.v1.Query/GetMarketMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// GetMarketMap returns the full market map stored in the x/marketmap
	// module.
	GetMarketMap(context.Context, *GetMarketMapRequest) (*GetMarketMapResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetMarketMap(ctx context.Context, req *GetMarketMapRequest) (*GetMarketMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketMap not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetMarketMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetMarketMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slinky.marketmap.v1.Query/GetMarketMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetMarketMap(ctx, req.(*GetMarketMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "slinky.marketmap.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarketMap",
			Handler:    _Query_GetMarketMap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slinky/marketmap/v1/query.proto",
}

func (m *GetMarketMapRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetMarketMapRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetMarketMapRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetMarketMapResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetMarketMapResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetMarketMapResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastUpdated != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LastUpdated))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.MarketMap.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetMarketMapRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetMarketMapResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MarketMap.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.LastUpdated != 0 {
		n += 1 + sovQuery(uint64(m.LastUpdated))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetMarketMapRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetMarketMapRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetMarketMapRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetMarketMapResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetMarketMapResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetMarketMapResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MarketMap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdated", wireType)
			}
			m.LastUpdated = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUpdated |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
